version: "v1.1.0"
author: "Roman Petrin"
port: ":8080"
db:
  connection: "user=blog dbname=blog host=localhost port=5432 password=blogPassword sslmode=false"
  schema: "public"
sendPulse:
  login: "rapetrin1"
  password: "123123"
  baseUrl: "baseUrl"
  sendUrl: "sendUrl"
  sender: "sender"
